#ifndef _MUFFIN_RENDER_FORMAT_H_
#define _MUFFIN_RENDER_FORMAT_H_

#include "muffin_core/common.h"

typedef enum MufFormat_e {
    MUF_FORMAT_F32,
    MUF_FORMAT_F32_2,
    MUF_FORMAT_F32_3,
    MUF_FORMAT_F32_4,

    MUF_FORMAT_F64,

    MUF_FORMAT_F16,
    MUF_FORMAT_F16_2,
    MUF_FORMAT_F16_3,
    MUF_FORMAT_F16_4,
    
    MUF_FORMAT_U8,
    MUF_FORMAT_U8_2,
    MUF_FORAMT_U8_3,
    MUF_FORMAT_U8_4,

    MUF_FORMAT_I8,
    MUF_FORMAT_I8_2,
    MUF_FORAMT_I8_3,
    MUF_FORMAT_I8_4,

    MUF_FORMAT_U16,
    MUF_FORMAT_U16_2,
    MUF_FORAMT_U16_3,
    MUF_FORMAT_U16_4,

    MUF_FORMAT_I16,
    MUF_FORMAT_I16_2,
    MUF_FORAMT_I16_3,
    MUF_FORMAT_I16_4,

    MUF_FORMAT_U32,
    MUF_FORMAT_U32_2,
    MUF_FORAMT_U32_3,
    MUF_FORMAT_U32_4,

    MUF_FORMAT_I32,
    MUF_FORMAT_I32_2,
    MUF_FORAMT_I32_3,
    MUF_FORMAT_I32_4,
} MufFormat;

#endif